services:
  - type: web
    name: poec-backend
    env: docker
    dockerContext: backend
    plan: free
    envVars:
      - key: POEC_ENV
        value: production
      - key: ANCHOR_CONTRACT_ADDRESS
        sync: false
      - key: ETHEREUM_NODE_URL
        value: https://rpc.sepolia.org
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    healthCheckPath: /health
